"""create workspace and insurance tables

Revision ID: 210abddf7a2d
Revises: 
Create Date: 2026-07-20 08:36:37.304094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210abddf7a2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('insurance_agents',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('npn', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_agents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_agents')),
    sa.UniqueConstraint('workspace_id', 'npn', name='uq_insurance_agents_workspace_npn')
    )
    op.create_index(op.f('ix_insurance_agents_workspace_id'), 'insurance_agents', ['workspace_id'], unique=False)
    op.create_table('insurance_carriers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_carriers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_carriers')),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_insurance_carriers_workspace_code')
    )
    op.create_index(op.f('ix_insurance_carriers_workspace_id'), 'insurance_carriers', ['workspace_id'], unique=False)
    op.create_table('insurance_customers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_customers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_customers')),
    sa.UniqueConstraint('workspace_id', 'customer_number', name='uq_insurance_customers_workspace_number')
    )
    op.create_index(op.f('ix_insurance_customers_workspace_id'), 'insurance_customers', ['workspace_id'], unique=False)
    op.create_table('insurance_plans',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('monthly_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['insurance_carriers.id'], name=op.f('fk_insurance_plans_carrier_id_insurance_carriers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_plans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_plans')),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_insurance_plans_workspace_code')
    )
    op.create_index(op.f('ix_insurance_plans_carrier_id'), 'insurance_plans', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_insurance_plans_workspace_id'), 'insurance_plans', ['workspace_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=50), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['insurance_agents.id'], name=op.f('fk_insurance_policies_agent_id_insurance_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['carrier_id'], ['insurance_carriers.id'], name=op.f('fk_insurance_policies_carrier_id_insurance_carriers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['insurance_customers.id'], name=op.f('fk_insurance_policies_customer_id_insurance_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], name=op.f('fk_insurance_policies_plan_id_insurance_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_policies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_policies')),
    sa.UniqueConstraint('workspace_id', 'source_system', 'source_record_id', name='uq_insurance_policies_workspace_source_record')
    )
    op.create_index(op.f('ix_insurance_policies_agent_id'), 'insurance_policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_carrier_id'), 'insurance_policies', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_customer_id'), 'insurance_policies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_plan_id'), 'insurance_policies', ['plan_id'], unique=False)
    op.create_index('ix_insurance_policies_workspace_policy_number', 'insurance_policies', ['workspace_id', 'policy_number'], unique=False)
    op.create_index('ix_insurance_policies_workspace_status', 'insurance_policies', ['workspace_id', 'status'], unique=False)
    op.create_table('insurance_commissions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['insurance_agents.id'], name=op.f('fk_insurance_commissions_agent_id_insurance_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], name=op.f('fk_insurance_commissions_policy_id_insurance_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_commissions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_commissions')),
    sa.UniqueConstraint('workspace_id', 'source_record_id', name='uq_insurance_commissions_workspace_source_record')
    )
    op.create_index(op.f('ix_insurance_commissions_agent_id'), 'insurance_commissions', ['agent_id'], unique=False)
    op.create_index('ix_insurance_commissions_workspace_policy', 'insurance_commissions', ['workspace_id', 'policy_id'], unique=False)
    op.create_table('insurance_payments',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], name=op.f('fk_insurance_payments_policy_id_insurance_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_insurance_payments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_payments')),
    sa.UniqueConstraint('workspace_id', 'source_record_id', name='uq_insurance_payments_workspace_source_record')
    )
    op.create_index('ix_insurance_payments_workspace_policy', 'insurance_payments', ['workspace_id', 'policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insurance_payments_workspace_policy', table_name='insurance_payments')
    op.drop_table('insurance_payments')
    op.drop_index('ix_insurance_commissions_workspace_policy', table_name='insurance_commissions')
    op.drop_index(op.f('ix_insurance_commissions_agent_id'), table_name='insurance_commissions')
    op.drop_table('insurance_commissions')
    op.drop_index('ix_insurance_policies_workspace_status', table_name='insurance_policies')
    op.drop_index('ix_insurance_policies_workspace_policy_number', table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_plan_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_customer_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_carrier_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_agent_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_insurance_plans_workspace_id'), table_name='insurance_plans')
    op.drop_index(op.f('ix_insurance_plans_carrier_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_insurance_customers_workspace_id'), table_name='insurance_customers')
    op.drop_table('insurance_customers')
    op.drop_index(op.f('ix_insurance_carriers_workspace_id'), table_name='insurance_carriers')
    op.drop_table('insurance_carriers')
    op.drop_index(op.f('ix_insurance_agents_workspace_id'), table_name='insurance_agents')
    op.drop_table('insurance_agents')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
