"""add document processing and extraction tables

Revision ID: 73489dd9db67
Revises: 221dccc688e2
Create Date: 2026-07-21 16:16:04.374674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73489dd9db67'
down_revision: Union[str, Sequence[str], None] = '221dccc688e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_runs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('processor_name', sa.String(length=100), server_default=sa.text("'insightops-document-extractor'"), nullable=False),
    sa.Column('processor_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('extracted_pages', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name=op.f('ck_document_processing_runs_status_valid')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_document_processing_runs_attempt_number_positive')),
    sa.CheckConstraint('extracted_pages >= 0', name=op.f('ck_document_processing_runs_extracted_pages_non_negative')),
    sa.CheckConstraint('total_pages IS NULL OR extracted_pages <= total_pages', name=op.f('ck_document_processing_runs_extracted_pages_within_total')),
    sa.CheckConstraint('total_pages IS NULL OR total_pages >= 0', name=op.f('ck_document_processing_runs_total_pages_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_processing_runs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_document_processing_runs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_document_processing_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_processing_runs')),
    sa.UniqueConstraint('document_id', 'attempt_number', name='document_attempt_unique')
    )
    op.create_index('ix_document_processing_runs_document_created', 'document_processing_runs', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_processing_runs_document_id'), 'document_processing_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_runs_requested_by_user_id'), 'document_processing_runs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_document_processing_runs_workspace_id'), 'document_processing_runs', ['workspace_id'], unique=False)
    op.create_index('ix_document_processing_runs_workspace_status', 'document_processing_runs', ['workspace_id', 'status'], unique=False)
    op.create_table('document_pages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('language_code', sa.String(length=20), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4, asdecimal=False), nullable=True),
    sa.Column('character_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('word_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_document_pages_status_valid')),
    sa.CheckConstraint('character_count >= 0', name=op.f('ck_document_pages_character_count_non_negative')),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1', name=op.f('ck_document_pages_confidence_score_valid')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_pages_page_number_positive')),
    sa.CheckConstraint('word_count >= 0', name=op.f('ck_document_pages_word_count_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['document_processing_runs.id'], name=op.f('fk_document_pages_processing_run_id_document_processing_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_document_pages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('processing_run_id', 'page_number', name='processing_run_page_unique')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index('ix_document_pages_document_page', 'document_pages', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_pages_processing_run_id'), 'document_pages', ['processing_run_id'], unique=False)
    op.create_index('ix_document_pages_processing_run_page', 'document_pages', ['processing_run_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_pages_workspace_id'), 'document_pages', ['workspace_id'], unique=False)
    op.create_index('ix_document_pages_workspace_status', 'document_pages', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_pages_workspace_status', table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_workspace_id'), table_name='document_pages')
    op.drop_index('ix_document_pages_processing_run_page', table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_processing_run_id'), table_name='document_pages')
    op.drop_index('ix_document_pages_document_page', table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index('ix_document_processing_runs_workspace_status', table_name='document_processing_runs')
    op.drop_index(op.f('ix_document_processing_runs_workspace_id'), table_name='document_processing_runs')
    op.drop_index(op.f('ix_document_processing_runs_requested_by_user_id'), table_name='document_processing_runs')
    op.drop_index(op.f('ix_document_processing_runs_document_id'), table_name='document_processing_runs')
    op.drop_index('ix_document_processing_runs_document_created', table_name='document_processing_runs')
    op.drop_table('document_processing_runs')
    # ### end Alembic commands ###
