from apps.api.app.services.auth import (
    AuthenticationError,
    DuplicateUserError,
    InactiveUserError,
    WorkspaceNotFoundError,
    authenticate_user,
    create_user,
    create_user_token_pair,
    get_user_by_email,
    get_user_by_id,
    get_workspace_by_slug,
    normalize_email,
    normalize_workspace_slug,
)
from apps.api.app.services.documents import (
    ALLOWED_CONTENT_TYPES,
    DOCUMENT_TYPE_BY_EXTENSION,
    MAX_DOCUMENT_SIZE_BYTES,
    DocumentTooLargeError,
    DocumentValidationError,
    InvalidDocumentSignatureError,
    UnsupportedDocumentTypeError,
    ValidatedDocument,
    calculate_sha256,
    get_file_extension,
    normalize_content_type,
    normalize_original_filename,
    validate_content_type,
    validate_document_upload,
    validate_file_signature,
    validate_file_size,
)
from apps.api.app.services.extraction import (
    DEFAULT_OCR_LANGUAGE,
    PDF_RENDER_DPI,
    SUPPORTED_EXTRACTION_EXTENSIONS,
    CorruptDocumentError,
    DocumentExtractionError,
    DocumentExtractionResult,
    ExtractedPage,
    ExtractionDependencyError,
    OCRTextResult,
    UnsupportedExtractionTypeError,
    extract_csv,
    extract_document,
    extract_excel,
    extract_image,
    extract_pdf,
    normalize_extracted_text,
)
from apps.api.app.services.storage import (
    DownloadedObject,
    StorageError,
    StorageObjectNotFoundError,
    StoredObject,
    build_storage_object_name,
    delete_object,
    download_object,
    ensure_storage_bucket,
    object_exists,
    sanitize_filename,
    upload_bytes,
    upload_stream,
)
from apps.api.app.services.document_processing import (
    MAX_PROCESSING_ERROR_LENGTH,
    PROCESSOR_NAME,
    PROCESSOR_VERSION,
    DocumentProcessingError,
    DocumentProcessingRunNotFoundError,
    ProcessingDocumentNotFoundError,
    build_document_page,
    build_extraction_metadata,
    create_document_processing_run,
    get_next_attempt_number,
    get_processing_run,
    mark_processing_run_failed,
    normalize_processing_error,
    process_document_run,
    utc_now,
)


__all__ = [
    # Authentication
    "AuthenticationError",
    "InactiveUserError",
    "DuplicateUserError",
    "WorkspaceNotFoundError",
    "normalize_email",
    "normalize_workspace_slug",
    "get_workspace_by_slug",
    "get_user_by_id",
    "get_user_by_email",
    "create_user",
    "authenticate_user",
    "create_user_token_pair",

    # Document validation
    "MAX_DOCUMENT_SIZE_BYTES",
    "ALLOWED_CONTENT_TYPES",
    "DOCUMENT_TYPE_BY_EXTENSION",
    "DocumentValidationError",
    "UnsupportedDocumentTypeError",
    "DocumentTooLargeError",
    "InvalidDocumentSignatureError",
    "ValidatedDocument",
    "normalize_original_filename",
    "get_file_extension",
    "normalize_content_type",
    "validate_content_type",
    "validate_file_size",
    "validate_file_signature",
    "calculate_sha256",
    "validate_document_upload",

    # Document extraction
    "DEFAULT_OCR_LANGUAGE",
    "PDF_RENDER_DPI",
    "SUPPORTED_EXTRACTION_EXTENSIONS",
    "DocumentExtractionError",
    "UnsupportedExtractionTypeError",
    "CorruptDocumentError",
    "ExtractionDependencyError",
    "OCRTextResult",
    "ExtractedPage",
    "DocumentExtractionResult",
    "normalize_extracted_text",
    "extract_pdf",
    "extract_image",
    "extract_csv",
    "extract_excel",
    "extract_document",

    # Object storage
    "StorageError",
    "StorageObjectNotFoundError",
    "StoredObject",
    "DownloadedObject",
    "ensure_storage_bucket",
    "sanitize_filename",
    "build_storage_object_name",
    "upload_bytes",
    "upload_stream",
    "download_object",
    "delete_object",
    "object_exists",
    
    # Document processing
    "PROCESSOR_NAME",
    "PROCESSOR_VERSION",
    "MAX_PROCESSING_ERROR_LENGTH",
    "DocumentProcessingError",
    "DocumentProcessingRunNotFoundError",
    "ProcessingDocumentNotFoundError",
    "utc_now",
    "normalize_processing_error",
    "get_next_attempt_number",
    "create_document_processing_run",
    "get_processing_run",
    "build_document_page",
    "build_extraction_metadata",
    "mark_processing_run_failed",
    "process_document_run",
]