from apps.api.app.services.auth import (
    AuthenticationError,
    DuplicateUserError,
    InactiveUserError,
    WorkspaceNotFoundError,
    authenticate_user,
    create_user,
    create_user_token_pair,
    get_user_by_email,
    get_user_by_id,
    get_workspace_by_slug,
    normalize_email,
    normalize_workspace_slug,
)
from apps.api.app.services.documents import (
    ALLOWED_CONTENT_TYPES,
    DOCUMENT_TYPE_BY_EXTENSION,
    MAX_DOCUMENT_SIZE_BYTES,
    DocumentTooLargeError,
    DocumentValidationError,
    InvalidDocumentSignatureError,
    UnsupportedDocumentTypeError,
    ValidatedDocument,
    calculate_sha256,
    get_file_extension,
    normalize_content_type,
    normalize_original_filename,
    validate_content_type,
    validate_document_upload,
    validate_file_signature,
    validate_file_size,
)
from apps.api.app.services.extraction import (
    DEFAULT_OCR_LANGUAGE,
    PDF_RENDER_DPI,
    SUPPORTED_EXTRACTION_EXTENSIONS,
    CorruptDocumentError,
    DocumentExtractionError,
    DocumentExtractionResult,
    ExtractedPage,
    ExtractionDependencyError,
    OCRTextResult,
    UnsupportedExtractionTypeError,
    extract_csv,
    extract_document,
    extract_excel,
    extract_image,
    extract_pdf,
    normalize_extracted_text,
)
from apps.api.app.services.storage import (
    DownloadedObject,
    StorageError,
    StorageObjectNotFoundError,
    StoredObject,
    build_storage_object_name,
    delete_object,
    download_object,
    ensure_storage_bucket,
    object_exists,
    sanitize_filename,
    upload_bytes,
    upload_stream,
)
from apps.api.app.services.document_processing import (
    MAX_PROCESSING_ERROR_LENGTH,
    PROCESSOR_NAME,
    PROCESSOR_VERSION,
    DocumentProcessingError,
    DocumentProcessingRunNotFoundError,
    ProcessingDocumentNotFoundError,
    build_document_page,
    build_extraction_metadata,
    create_document_processing_run,
    get_next_attempt_number,
    get_processing_run,
    mark_processing_run_failed,
    normalize_processing_error,
    process_document_run,
    utc_now,
)
from apps.api.app.services.rag_chunking import (
    BREAK_SEPARATORS,
    DEFAULT_CHUNK_OVERLAP_CHARACTERS,
    DEFAULT_CHUNK_SIZE_CHARACTERS,
    MINIMUM_BREAK_RATIO,
    DocumentChunkingError,
    SourceDocumentPage,
    TextChunk,
    calculate_chunk_sha256,
    chunk_document_pages,
    chunk_page_text,
    validate_chunking_parameters,
)
from apps.api.app.services.rag_embeddings import (
    EMBEDDING_PROVIDER_NAME,
    DenseEmbeddingModel,
    EmbeddingBatch,
    EmbeddingDimensionError,
    EmbeddingGenerationError,
    EmbeddingServiceError,
    InvalidEmbeddingInputError,
    embed_passages,
    embed_query,
    get_embedding_model,
    normalize_embedding_text,
    normalize_embedding_vector,
    normalize_passage_inputs,
    validate_embedding_configuration,
)
from apps.api.app.services.rag_indexing import (
    RAGIndexingError,
    RAGIndexingResult,
    build_document_chunk_models,
    build_source_document_pages,
    index_document_pages,
)
from apps.api.app.services.rag_retrieval import (
    InvalidRAGSearchError,
    RAGRetrievalError,
    RAGSearchDatabaseError,
    RAGSearchHit,
    RAGSearchResult,
    build_rag_search_hit,
    cosine_distance_to_similarity,
    normalize_document_ids,
    normalize_rag_query,
    resolve_rag_top_k,
    search_document_chunks,
    validate_minimum_similarity,
)
from apps.api.app.services.rag_answering import (
    DEFAULT_MAX_CITATIONS,
    MAX_ALLOWED_CITATIONS,
    MAX_CITATION_EXCERPT_CHARACTERS,
    GroundedRAGAnswer,
    InvalidRAGAnswerRequestError,
    RAGAnsweringError,
    RAGCitation,
    answer_document_question,
    build_grounded_answer,
    build_rag_citations,
    calculate_answer_confidence,
    compose_grounded_answer,
    extract_best_answer_excerpt,
    normalize_answer_question,
    resolve_max_citations,
    score_answer_sentence,
    split_answer_sentences,
    tokenize_answer_text,
    truncate_citation_excerpt,
)
from apps.api.app.services.sql_agent_guardrails import (
    SQL_AGENT_ALLOWED_SCHEMAS,
    SQL_AGENT_ALLOWED_TABLES,
    EmptySQLQueryError,
    InvalidSQLAgentLimitError,
    MissingSQLDataSourceError,
    MultipleSQLStatementsError,
    NonReadOnlySQLQueryError,
    SafeSQLValidationResult,
    SQLAgentGuardrailError,
    SQLParsingError,
    SQLQueryTooLongError,
    UnauthorizedSQLTableError,
    UnsafeSQLFunctionError,
    build_row_limited_sql,
    validate_sql_agent_query,
)
from apps.api.app.services.sql_agent_executor import (
    POSTGRES_QUERY_CANCELLED_SQLSTATE,
    InvalidSQLAgentTimeoutError,
    SQLAgentConnectionError,
    SQLAgentDatabaseError,
    SQLAgentExecutionError,
    SQLAgentExecutionResult,
    SQLAgentTimeoutError,
    execute_validated_sql,
    extract_database_sqlstate,
    is_statement_timeout_error,
    open_sql_agent_connection,
    resolve_statement_timeout_ms,
    serialize_sql_row,
    serialize_sql_value,
    validate_and_execute_sql,
)
from apps.api.app.services.sql_agent_planner import (
    EmptySQLAgentQuestionError,
    SQLAgentIntent,
    SQLAgentPlan,
    SQLAgentPlannerError,
    SQLAgentQuestionTooLongError,
    UnsupportedSQLAgentQuestionError,
    build_sql_for_intent,
    detect_sql_agent_intent,
    normalize_sql_agent_question,
    plan_sql_agent_question,
)

from apps.api.app.services.sql_agent_schema import (
    InsuranceSchemaCatalog,
    InvalidSQLAgentIdentifierError,
    MissingSQLAgentColumnError,
    MissingSQLAgentTableError,
    SQLAgentColumnCatalog,
    SQLAgentRelationship,
    SQLAgentSchemaError,
    SQLAgentTableCatalog,
    build_schema_catalog_from_mapping,
    load_insurance_schema_catalog,
    validate_schema_identifier,
)


__all__ = [
    # Authentication
    "AuthenticationError",
    "InactiveUserError",
    "DuplicateUserError",
    "WorkspaceNotFoundError",
    "normalize_email",
    "normalize_workspace_slug",
    "get_workspace_by_slug",
    "get_user_by_id",
    "get_user_by_email",
    "create_user",
    "authenticate_user",
    "create_user_token_pair",

    # Document validation
    "MAX_DOCUMENT_SIZE_BYTES",
    "ALLOWED_CONTENT_TYPES",
    "DOCUMENT_TYPE_BY_EXTENSION",
    "DocumentValidationError",
    "UnsupportedDocumentTypeError",
    "DocumentTooLargeError",
    "InvalidDocumentSignatureError",
    "ValidatedDocument",
    "normalize_original_filename",
    "get_file_extension",
    "normalize_content_type",
    "validate_content_type",
    "validate_file_size",
    "validate_file_signature",
    "calculate_sha256",
    "validate_document_upload",

    # Document extraction
    "DEFAULT_OCR_LANGUAGE",
    "PDF_RENDER_DPI",
    "SUPPORTED_EXTRACTION_EXTENSIONS",
    "DocumentExtractionError",
    "UnsupportedExtractionTypeError",
    "CorruptDocumentError",
    "ExtractionDependencyError",
    "OCRTextResult",
    "ExtractedPage",
    "DocumentExtractionResult",
    "normalize_extracted_text",
    "extract_pdf",
    "extract_image",
    "extract_csv",
    "extract_excel",
    "extract_document",

    # Object storage
    "StorageError",
    "StorageObjectNotFoundError",
    "StoredObject",
    "DownloadedObject",
    "ensure_storage_bucket",
    "sanitize_filename",
    "build_storage_object_name",
    "upload_bytes",
    "upload_stream",
    "download_object",
    "delete_object",
    "object_exists",
    
    # Document processing
    "PROCESSOR_NAME",
    "PROCESSOR_VERSION",
    "MAX_PROCESSING_ERROR_LENGTH",
    "DocumentProcessingError",
    "DocumentProcessingRunNotFoundError",
    "ProcessingDocumentNotFoundError",
    "utc_now",
    "normalize_processing_error",
    "get_next_attempt_number",
    "create_document_processing_run",
    "get_processing_run",
    "build_document_page",
    "build_extraction_metadata",
    "mark_processing_run_failed",
    "process_document_run",
    
    # RAG chunking
    "DEFAULT_CHUNK_SIZE_CHARACTERS",
    "DEFAULT_CHUNK_OVERLAP_CHARACTERS",
    "MINIMUM_BREAK_RATIO",
    "BREAK_SEPARATORS",
    "DocumentChunkingError",
    "SourceDocumentPage",
    "TextChunk",
    "calculate_chunk_sha256",
    "validate_chunking_parameters",
    "chunk_page_text",
    "chunk_document_pages",
    
    # RAG embeddings
    "EMBEDDING_PROVIDER_NAME",
    "DenseEmbeddingModel",
    "EmbeddingBatch",
    "EmbeddingServiceError",
    "InvalidEmbeddingInputError",
    "EmbeddingDimensionError",
    "EmbeddingGenerationError",
    "normalize_embedding_text",
    "normalize_passage_inputs",
    "normalize_embedding_vector",
    "validate_embedding_configuration",
    "get_embedding_model",
    "embed_passages",
    "embed_query",
    
    # RAG indexing
    "RAGIndexingError",
    "RAGIndexingResult",
    "build_source_document_pages",
    "build_document_chunk_models",
    "index_document_pages",
    
    # RAG retrieval
    "RAGRetrievalError",
    "InvalidRAGSearchError",
    "RAGSearchDatabaseError",
    "RAGSearchHit",
    "RAGSearchResult",
    "normalize_rag_query",
    "resolve_rag_top_k",
    "validate_minimum_similarity",
    "normalize_document_ids",
    "cosine_distance_to_similarity",
    "build_rag_search_hit",
    "search_document_chunks",
    
    # RAG answering
    "DEFAULT_MAX_CITATIONS",
    "MAX_ALLOWED_CITATIONS",
    "MAX_CITATION_EXCERPT_CHARACTERS",
    "RAGAnsweringError",
    "InvalidRAGAnswerRequestError",
    "RAGCitation",
    "GroundedRAGAnswer",
    "normalize_answer_question",
    "resolve_max_citations",
    "tokenize_answer_text",
    "split_answer_sentences",
    "truncate_citation_excerpt",
    "score_answer_sentence",
    "extract_best_answer_excerpt",
    "build_rag_citations",
    "calculate_answer_confidence",
    "compose_grounded_answer",
    "build_grounded_answer",
    "answer_document_question",
    
    # SQL Agent guardrails
    "SQL_AGENT_ALLOWED_SCHEMAS",
    "SQL_AGENT_ALLOWED_TABLES",
    "SQLAgentGuardrailError",
    "EmptySQLQueryError",
    "SQLQueryTooLongError",
    "SQLParsingError",
    "MultipleSQLStatementsError",
    "NonReadOnlySQLQueryError",
    "UnauthorizedSQLTableError",
    "UnsafeSQLFunctionError",
    "MissingSQLDataSourceError",
    "InvalidSQLAgentLimitError",
    "SafeSQLValidationResult",
    "build_row_limited_sql",
    "validate_sql_agent_query",
    
    # SQL Agent execution
    "POSTGRES_QUERY_CANCELLED_SQLSTATE",
    "SQLAgentExecutionError",
    "SQLAgentDatabaseError",
    "SQLAgentTimeoutError",
    "InvalidSQLAgentTimeoutError",
    "SQLAgentConnectionError",
    "SQLAgentExecutionResult",
    "resolve_statement_timeout_ms",
    "serialize_sql_value",
    "serialize_sql_row",
    "extract_database_sqlstate",
    "is_statement_timeout_error",
    "open_sql_agent_connection",
    "execute_validated_sql",
    "validate_and_execute_sql",
    
    # SQL Agent schema
    "SQLAgentSchemaError",
    "MissingSQLAgentTableError",
    "MissingSQLAgentColumnError",
    "InvalidSQLAgentIdentifierError",
    "SQLAgentColumnCatalog",
    "SQLAgentRelationship",
    "SQLAgentTableCatalog",
    "InsuranceSchemaCatalog",
    "validate_schema_identifier",
    "build_schema_catalog_from_mapping",
    "load_insurance_schema_catalog",

    # SQL Agent planner
    "SQLAgentPlannerError",
    "EmptySQLAgentQuestionError",
    "SQLAgentQuestionTooLongError",
    "UnsupportedSQLAgentQuestionError",
    "SQLAgentIntent",
    "SQLAgentPlan",
    "normalize_sql_agent_question",
    "detect_sql_agent_intent",
    "build_sql_for_intent",
    "plan_sql_agent_question",
        
]